### ISSUE TITLE
[Mac] Path to Resources is Wrong

### ISSUE THREAD

**Issue by gerwinbrunner** [jaruba/wcjs-player#11]
It seems that the resource loading (css, png, fonts) is not working when using an app:// url in node webkit.

**Comment by jaruba** [comment]
I have it working on: ``app://host/index.html``

Please download the master from: https://github.com/jaruba/node-vlcPlayer-demo

Just follow the install instruction and tell me if it works for you. (it also uses the ``app://`` protocol)

**Comment by gerwinbrunner** [comment]
Nope, it does not work. I get the following error
´´´
[8396:0723/130046:ERROR:nw_shell.cc(335)] Error: dlopen(/Users/ap/Documents/workspaces/github-workspace/node-vlcPlayer-demo/node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/build/Release/WebChimera.js.node, 1): Library not loaded: @loader_path/lib/libvlc.5.dylib
  Referenced from: /Users/ap/Documents/workspaces/github-workspace/node-vlcPlayer-demo/node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/build/Release/WebChimera.js.node
  Reason: image not found
    at Error (native)
    at Module.load (module.js:346:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:356:17)
    at require (module.js:375:17)
    at bindings (/Users/ap/Documents/workspaces/github-workspace/node-vlcPlayer-demo/node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/ap/Documents/workspaces/github-workspace/node-vlcPlayer-demo/node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/index.js:1:99)
    at Module._compile (module.js:451:26)
    at Object.Module._extensions..js (module.js:469:10)
    at Module.load (module.js:346:32)
[8396:0723/130046:INFO:CONSOLE(83)] "Uncaught Error: dlopen(/Users/ap/Documents/workspaces/github-workspace/node-vlcPlayer-demo/node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/build/Release/WebChimera.js.node, 1): Library not loaded: @loader_path/lib/libvlc.5.dylib
  Referenced from: /Users/ap/Documents/workspaces/github-workspace/node-vlcPlayer-demo/node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/build/Release/WebChimera.js.node
  Reason: image not found", source: /Users/ap/Documents/workspaces/github-workspace/node-vlcPlayer-demo/node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/node_modules/bindings/bindings.js (83)

´´´

**Comment by jaruba** [comment]
[8396:0723/130046:ERROR:nw_shell.cc(335)] Error: dlopen(/Users/ap/Documents/workspaces/github-workspace/node-vlcPlayer-demo/node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/build/Release/WebChimera.js.node, 1): Library not loaded: @loader_path/lib/libvlc.5.dylib

``WebChimera.js`` is not loading properly, did you add libvlc binaries to the app root?

**Comment by jaruba** [comment]
Here is a previous discussion about getting ``WebChimera.js`` to work on Mac:
https://github.com/jaruba/wcjs-player/issues/7#issuecomment-120457414

**Comment by gerwinbrunner** [comment]
You are right. I needed to download the zip and copy its content (lib folder) to the folder `node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/build/Release`

Then I was able to start the app and the video played, but the controls did still not work.

```
Failed to load resource: net::ERR_FILE_NOT_FOUND
app://host/Users/ap/Documents/workspaces/github-workspace/node-vlcPlayer-demo/node_modules/wcjs-player/images/dragger.png Failed to load resource: net::ERR_FILE_NOT_FOUND
Users/ap/Documents/workspaces/github-workspace/node-vlcPlayer-demo/node_modules/wcjs-player/dst/computer-sleep/resources/muted-blank.mp4:1 GET app://host/Users/ap/Documents/workspaces/github-workspace/node-vlcPlayer-demo/node_modules/wcjs-player/dst/computer-sleep/resources/muted-blank.mp4 net::ERR_FILE_NOT_FOUND
Users/ap/Documents/workspaces/github-workspace/node-vlcPlayer-demo/node_modules/wcjs-player/dst/computer-sleep/resources/muted-blank.ogv:1 GET app://host/Users/ap/Documents/workspaces/github-workspace/node-vlcPlayer-demo/node_modules/wcjs-player/dst/computer-sleep/resources/muted-blank.ogv net::ERR_FILE_NOT_FOUND```

**Comment by jaruba** [comment]
the path to the files looks correct to me, can you try changing the URL in the NW.js window with:

    app://host/Users/ap/Documents/workspaces/github-workspace/node-vlcPlayer-demo/node_modules/wcjs-player/images/dragger.png

and see if the image is displayed? (it should be just a small image with some dots)

**Comment by jaruba** [comment]
oh, I see the problem! give me a second to think what I can do about it :)

**Comment by jaruba** [comment]
- open ``index.js`` with any code editor, search for: ``__dirname``, change them to ``file:///'+__dirname`` or ``file:///"+__dirname``, depending of the circumstane.

- open ``dst/computer-sleep/sleep.js``, search for ``__dirname``, change them to ``"file:///"+__dirname``

- try loading your app again

if this works for you, I'll test it on windows too and commit the fix.

**Comment by gerwinbrunner** [comment]
I just figured out that it would be somehow better to use relative urls and stick to the app paths.
I created an pull request with the fix.

https://github.com/jaruba/wcjs-player/pull/12

**Comment by jaruba** [comment]
Works great on Windows too, thanks. :)

**Comment by gerwinbrunner** [comment]
Thanks for merging so quickly. 
When do you plan to release the next version to nom?

**Comment by jaruba** [comment]
Probably in an hour or two. (maybe sooner)

I have one more major code optimization to do before I publish the new version.

**Comment by gerwinbrunner** [comment]
Oh cool. Thx!

**Comment by gerwinbrunner** [comment]
Just found an error, fixed it and created a new pull request.
https://github.com/jaruba/wcjs-player/pull/13

**Comment by jaruba** [comment]
published, sorry it took so long
