### ISSUE TITLE
Error on startup in windows 7 64bit

### ISSUE THREAD

**Issue by wildeyes** [jaruba/wcjs-player#60]
I ran `npm i -g electron-prebuilt && electron index.js`.

```
App threw an error during load
Error: Cannot find module 'core-util-is'
    at Module._resolveFilename (module.js:438:15)
    at Function.Module._resolveFilename (C:\Users\xxx\AppData\Roaming\npm\node_modules\electron-prebuilt\dist\resources\electron.asar\common\reset-search-paths.js:47:12)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\code\wcjs-player\node_modules\readable-stream\lib\_stream_duplex.js:25:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
```

**Comment by jaruba** [comment]
What electron version is it installing?

**Comment by jaruba** [comment]
try doing `npm install core-util-is` in the `C:\code\wcjs-player\` folder, maybe? :)
