### ISSUE TITLE
$.extend is not a function

### ISSUE THREAD

**Issue by YugoCode** [jaruba/wcjs-player#77]
I would like to play HEVC/H.265 encoded video streams inside an electron application.

So I found wcjs-player and installed it with:
`npm install wcjs-player
`

And then:
```
git clone --recursive https://github.com/RSATom/WebChimera.js.git
cd WebChimera.js
./build_nwjs.sh
```

When I use `var wjs = require("wcjs-player");`

I get this error:

> TypeError: $.extend is not a function
>     at /home/payam/Documents/awt-tv-web-app/node_modules/jquery-ui/core.js:21:3
>     at Object.<anonymous> (/home/payam/Documents/awt-tv-web-app/node_modules/jquery-ui/core.js:322:3)
>     at Module._compile (module.js:556:32)
>     at Object.Module._extensions..js (module.js:565:10)
>     at Module.load (module.js:473:32)
>     at tryModuleLoad (module.js:432:12)
>     at Function.Module._load (module.js:424:3)
>     at Module.require (module.js:483:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/home/payam/Documents/awt-tv-web-app/node_modules/jquery-ui/sortable.js:2:1)
> A JavaScript error occurred in the main process
> Uncaught Exception:
> TypeError: $.extend is not a function
>     at /home/payam/Documents/awt-tv-web-app/node_modules/jquery-ui/core.js:21:3
>     at Object.<anonymous> (/home/payam/Documents/awt-tv-web-app/node_modules/jquery-ui/core.js:322:3)
>     at Module._compile (module.js:556:32)
>     at Object.Module._extensions..js (module.js:565:10)
>     at Module.load (module.js:473:32)
>     at tryModuleLoad (module.js:432:12)
>     at Function.Module._load (module.js:424:3)
>     at Module.require (module.js:483:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/home/payam/Documents/awt-tv-web-app/node_modules/jquery-ui/sortable.js:2:1)

What's the problem here? I used an empty electron test project, so I didn't require any other things.

**Comment by jacopocarlini** [comment]
I solved by re-installing wcjs-player. It is because wcjs-player use a modded version of jquery, I think.

**Comment by Chris763454357** [comment]
How exactly did you fix this? I have the same issue. From my understanding this happens because when jQuery does not have access to a real window object instead of returning jQeury instance it just returns the factory that can be used to create the jQuery instance (which is obviously missing the extend method).

So to fix this error it seems I need to somehow create an HTML document with the window property so jQuery can 'hook' into the DOM of that page. The instructions show me the JS code and the HTML code but I don't know where/how to use that HTML code (just started learning node, instruction unclear :P)

**Comment by jacopocarlini** [comment]
I deleted the directory named "node_modules". Then I re-installed first all others modules and at **last** wcjs
